# Generated by Django 6.0.1 on 2026-02-14 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
